USE escola;
USE enpresa;
CREATE TABLE FUNCIONARIOS(
ID_FUNCIONARIOS INT,
NOME_PRODUTOS VARCHAR(100),
CARGO VARCHAR(30),
SALARIO INT);

CREATE TABLE DEPARTAMENTOS(
ID_DEPARTAMENTO INT,
NOME_DEPARTAMENTOS VARCHAR(50)
);
INSERT INTO FUNCIONARIOS VALUES
(1, 'ANA SILVA', 'GERENTE', 8000.00),
(2, 'CARLOS PEREIRA', 'ANALISTA', 45000.00),
(3, 'MARIA SANTOS', 'ASSISTENTE', 3000.00),
(4, ' JOÃO OLIVEIRA', 'DESENVOLVEDOR', 6000.00),
(5,'FERNANDA COSTA','CONTADORA', 5500.00);

SELECT NOME_PRODUTOS,CARGO FROM FUNCIONARIOS;
SELECT NOME_DEPARTAMENTOS FROM DEPARTAMENTOS;  
